import requests
from bs4 import BeautifulSoup
import pandas as pd

# List of URLs to scrape
urls = [
    "https://www.ultimatecarpage.com/car/4407/Ferrari-F10.html",
    "https://www.ultimatecarpage.com/car/4426/Force-India-VJM03-Mercedes.html",
    "https://www.ultimatecarpage.com/car/4434/Lotus-T127-Cosworth.html",
    "https://www.ultimatecarpage.com/car/4402/McLaren-MP4-25-Mercedes.html",
    "https://www.ultimatecarpage.com/car/4401/Mercedes-Benz-W01.html",
    "https://www.ultimatecarpage.com/car/4417/Red-Bull-Racing-RB6-Renault.html",
    "https://www.ultimatecarpage.com/car/4412/Renault-R30.html",
    "https://www.ultimatecarpage.com/car/4413/Sauber-C29-Ferrari.html",
    "https://www.ultimatecarpage.com/car/4416/Toro-Rosso-STR5-Ferrari.html",
    "https://www.ultimatecarpage.com/car/4420/Virgin-VR-01-Cosworth.html",
    "https://www.ultimatecarpage.com/car/4403/Williams-FW32-Cosworth.html",
    "https://www.ultimatecarpage.com/car/4014/BMW-Sauber-F1.09.html",
    "https://www.ultimatecarpage.com/car/4092/Brawn-GP-BGP001-Mercedes.html",
    "https://www.ultimatecarpage.com/car/4000/Ferrari-F60.html",
    "https://www.ultimatecarpage.com/car/4072/Force-India-VJM02-Mercedes.html",
    "https://www.ultimatecarpage.com/car/4011/McLaren-MP4-24-Mercedes.html",
    "https://www.ultimatecarpage.com/car/4038/Red-Bull-Racing-RB5-Renault.html",
    "https://www.ultimatecarpage.com/car/4013/Renault-R29.html",
    "https://www.ultimatecarpage.com/car/4090/Toro-Rosso-STR4-Ferrari.html",
    "https://www.ultimatecarpage.com/car/4010/Toyota-TF109.html",
    "https://www.ultimatecarpage.com/car/4012/Williams-FW31-Toyota.html",
    "https://www.ultimatecarpage.com/car/3576/BMW-Sauber-F1.08.html",
    "https://www.ultimatecarpage.com/car/3543/Ferrari-F2008.html",
    "https://www.ultimatecarpage.com/car/3604/Force-India-VJM01-Ferrari.html",
    "https://www.ultimatecarpage.com/car/3591/Honda-RA108.html",
    "https://www.ultimatecarpage.com/car/3544/McLaren-MP4-23-Mercedes.html",
    "https://www.ultimatecarpage.com/car/3589/Renault-R28.html",
    "https://www.ultimatecarpage.com/car/7684/Toro-Rosso-STR3-Ferrari.html",
    "https://www.ultimatecarpage.com/car/3554/Toyota-TF108.html",
    "https://www.ultimatecarpage.com/car/3580/Williams-FW30-Toyota.html",
    "https://www.ultimatecarpage.com/car/3077/BMW-Sauber-F1.07.html",
    "https://www.ultimatecarpage.com/car/3068/Ferrari-F2007.html",
    "https://www.ultimatecarpage.com/car/3085/Honda-RA107.html",
    "https://www.ultimatecarpage.com/car/3078/McLaren-MP4-22-Mercedes.html",
    "https://www.ultimatecarpage.com/car/3089/Red-Bull-Racing-RB3-Renault.html",
    "https://www.ultimatecarpage.com/car/3082/Renault-R27.html",
    "https://www.ultimatecarpage.com/car/3095/Spyker-F8-VII-Ferrari.html",
    "https://www.ultimatecarpage.com/car/3059/Toyota-TF107.html",
    "https://www.ultimatecarpage.com/car/3091/Williams-FW29-Toyota.html",
    "https://www.ultimatecarpage.com/car/2663/BMW-Sauber-F1.06.html",
    "https://www.ultimatecarpage.com/car/2669/Ferrari-248-F1.html",
    "https://www.ultimatecarpage.com/car/2692/Honda-RA106.html",
    "https://www.ultimatecarpage.com/car/2670/McLaren-MP4-21-Mercedes.html",
    "https://www.ultimatecarpage.com/car/2678/Renault-R26.html",
    "https://www.ultimatecarpage.com/car/2589/Toyota-TF106.html",
    "https://www.ultimatecarpage.com/car/2691/Williams-FW28-Cosworth.html",
    "https://www.ultimatecarpage.com/car/2234/BAR-007-Honda.html",
    "https://www.ultimatecarpage.com/car/2233/Ferrari-F2005.html",
    "https://www.ultimatecarpage.com/car/2237/McLaren-MP4-20-Mercedes.html",
    "https://www.ultimatecarpage.com/car/2311/Minardi-PS05-Cosworth.html",
    "https://www.ultimatecarpage.com/car/2236/Renault-R25.html",
    "https://www.ultimatecarpage.com/car/2235/Toyota-TF105.html",
    "https://www.ultimatecarpage.com/car/2207/Williams-FW27-BMW.html",
    "https://www.ultimatecarpage.com/car/1882/BAR-006-Honda.html",
    "https://www.ultimatecarpage.com/car/1863/Ferrari-F2004.html",
    "https://www.ultimatecarpage.com/car/1857/Jaguar-R5.html",
    "https://www.ultimatecarpage.com/car/1896/Jordan-EJ14-Ford.html",
    "https://www.ultimatecarpage.com/car/1811/McLaren-MP4-19-Mercedes.html",
    "https://www.ultimatecarpage.com/car/2004/McLaren-MP4-19B-Mercedes.html",
    "https://www.ultimatecarpage.com/car/1971/Minardi-PS04B-Cosworth.html",
    "https://www.ultimatecarpage.com/car/1886/Renault-R24.html",
    "https://www.ultimatecarpage.com/car/1858/Toyota-TF104.html",
    "https://www.ultimatecarpage.com/car/1855/Williams-FW26-BMW.html",
    "https://www.ultimatecarpage.com/car/1592/BAR-005-Honda.html",
    "https://www.ultimatecarpage.com/car/1237/Ferrari-F2002.html",
    "https://www.ultimatecarpage.com/car/1606/Ferrari-F2003-GA.html",
    "https://www.ultimatecarpage.com/car/1597/Jaguar-R4.html",
    "https://www.ultimatecarpage.com/car/972/Jordan-EJ13-Ford.html",
    "https://www.ultimatecarpage.com/car/1637/McLaren-MP4-17D-Mercedes.html",
    "https://www.ultimatecarpage.com/car/1678/McLaren-MP4-18-Mercedes.html",
    "https://www.ultimatecarpage.com/car/1625/Minardi-PS03-Cosworth.html",
    "https://www.ultimatecarpage.com/car/1596/Renault-R203.html",
    "https://www.ultimatecarpage.com/car/1608/Sauber-C22-Petronas.html",
    "https://www.ultimatecarpage.com/car/1593/Toyota-TF103.html",
    "https://www.ultimatecarpage.com/car/1602/Williams-FW25-BMW.html",
    "https://www.ultimatecarpage.com/car/1250/Arrows-A23-Cosworth.html",
    "https://www.ultimatecarpage.com/car/1115/BAR-004-Honda.html",
    "https://www.ultimatecarpage.com/car/1237/Ferrari-F2002.html",
    "https://www.ultimatecarpage.com/car/992/Jaguar-R3.html",
    "https://www.ultimatecarpage.com/car/1264/Jordan-EJ12-Honda.html",
    "https://www.ultimatecarpage.com/car/1209/McLaren-MP4-17-Mercedes.html",
    "https://www.ultimatecarpage.com/car/1232/Minardi-PS02-Asiatech.html",
    "https://www.ultimatecarpage.com/car/1275/Renault-R202.html",
    "https://www.ultimatecarpage.com/car/1222/Sauber-C21-Petronas.html",
    "https://www.ultimatecarpage.com/car/1114/Toyota-TF102.html",
    "https://www.ultimatecarpage.com/car/1201/Williams-FW24-BMW.html",
    "https://www.ultimatecarpage.com/car/1061/Arrows-A22-Asiatech.html",
    "https://www.ultimatecarpage.com/car/41/BAR-003-Honda.html",
    "https://www.ultimatecarpage.com/car/507/Benetton-B201-Renault.html",
    "https://www.ultimatecarpage.com/car/199/Ferrari-F2001.html",
    "https://www.ultimatecarpage.com/car/231/Jaguar-R2.html",
    "https://www.ultimatecarpage.com/car/235/Jordan-EJ11-Honda.html",
    "https://www.ultimatecarpage.com/car/508/McLaren-MP4-16-Mercedes.html",
    "https://www.ultimatecarpage.com/car/1069/Minardi-PS01-Eurotech.html",
    "https://www.ultimatecarpage.com/car/458/Sauber-C20-Petronas.html",
    "https://www.ultimatecarpage.com/car/505/Williams-FW23-BMW.html",
    "https://www.ultimatecarpage.com/car/7843/Alfa-Romeo-Racing-C39-Ferrari.html",
    "https://www.ultimatecarpage.com/car/7842/AlphaTauri-AT01-Honda.html",
    "https://www.ultimatecarpage.com/car/7839/Ferrari-SF1000.html",
    "https://www.ultimatecarpage.com/car/7848/Haas-VF-20-Ferrari.html",
    "https://www.ultimatecarpage.com/car/7840/McLaren-MCL35-Renault.html",
    "https://www.ultimatecarpage.com/car/7847/Mercedes-Benz-W11-EQ-Performance.html",
    "https://www.ultimatecarpage.com/car/7845/Racing-Point-RP20-Mercedes.html",
    "https://www.ultimatecarpage.com/car/7841/Red-Bull-Racing-RB16-Honda.html",
    "https://www.ultimatecarpage.com/car/7844/Renault-R.S.-20.html",
    "https://www.ultimatecarpage.com/car/7846/Williams-FW43-Mercedes.html",
    "https://www.ultimatecarpage.com/car/7547/Alfa-Romeo-Racing-C38-Ferrari.html",
    "https://www.ultimatecarpage.com/car/7540/Ferrari-SF90.html",
    "https://www.ultimatecarpage.com/car/7542/Haas-VF-19-Ferrari.html",
    "https://www.ultimatecarpage.com/car/7543/McLaren-MCL34-Renault.html",
    "https://www.ultimatecarpage.com/car/7544/Mercedes-Benz-W10-EQ-Power-.html",
    "https://www.ultimatecarpage.com/car/7541/Racing-Point-RP19-Mercedes.html",
    "https://www.ultimatecarpage.com/car/7545/Red-Bull-Racing-RB15-Honda.html",
    "https://www.ultimatecarpage.com/car/7546/Renault-R.S.-19.html",
    "https://www.ultimatecarpage.com/car/7548/Toro-Rosso-STR14-Honda.html",
    "https://www.ultimatecarpage.com/car/7549/Williams-FW42-Mercedes.html",
    "https://www.ultimatecarpage.com/car/7046/Ferrari-SF71H.html",
    "https://www.ultimatecarpage.com/car/7045/Force-India-VJM11-Mercedes.html",
    "https://www.ultimatecarpage.com/car/7037/Haas-VF-18-Ferrari.html",
    "https://www.ultimatecarpage.com/car/7041/McLaren-MCL33-Renault.html",
    "https://www.ultimatecarpage.com/car/7040/Mercedes-Benz-W09-EQ-Power-.html",
    "https://www.ultimatecarpage.com/car/7044/Red-Bull-Racing-RB14-Tag-Heuer.html",
    "https://www.ultimatecarpage.com/car/7042/Renault-R.S.-18.html",
    "https://www.ultimatecarpage.com/car/7038/Sauber-C37-Ferrari.html",
    "https://www.ultimatecarpage.com/car/7043/Toro-Rosso-STR13-Honda.html",
    "https://www.ultimatecarpage.com/car/7039/Williams-FW41-Mercedes.html",
    "https://www.ultimatecarpage.com/car/6775/Ferrari-SF70H.html",
    "https://www.ultimatecarpage.com/car/6779/Force-India-VJM10-Mercedes.html",
    "https://www.ultimatecarpage.com/car/6783/Haas-VF-17-Ferrari.html",
    "https://www.ultimatecarpage.com/car/6776/McLaren-MCL32-Honda.html",
    "https://www.ultimatecarpage.com/car/6777/Mercedes-Benz-W08-EQ-Power-.html",
    "https://www.ultimatecarpage.com/car/6780/Red-Bull-Racing-RB13-Tag-Heuer.html",
    "https://www.ultimatecarpage.com/car/6781/Renault-R.S.17.html",
    "https://www.ultimatecarpage.com/car/6778/Sauber-C36-Ferrari.html",
    "https://www.ultimatecarpage.com/car/6782/Toro-Rosso-STR12-Renault.html",
    "https://www.ultimatecarpage.com/car/6774/Williams-FW40-Mercedes.html",
    "https://www.ultimatecarpage.com/car/6491/Ferrari-SF16-H.html",
    "https://www.ultimatecarpage.com/car/6495/Force-India-VJM09-Mercedes.html",
    "https://www.ultimatecarpage.com/car/6496/Haas-VF-16-Ferrari.html",
    "https://www.ultimatecarpage.com/car/6490/McLaren-MP4-31-Honda.html",
    "https://www.ultimatecarpage.com/car/6492/Mercedes-Benz-W07-Hybrid.html",
    "https://www.ultimatecarpage.com/car/6497/Red-Bull-Racing-RB12-Tag-Heuer.html",
    "https://www.ultimatecarpage.com/car/6478/Renault-R.S.-16.html",
    "https://www.ultimatecarpage.com/car/6494/Sauber-C35-Ferrari.html",
    "https://www.ultimatecarpage.com/car/6498/Toro-Rosso-STR11-Ferrari.html",
    "https://www.ultimatecarpage.com/car/6493/Williams-FW38-Mercedes.html",
    "https://www.ultimatecarpage.com/car/6096/Ferrari-SF15-T.html",
    "https://www.ultimatecarpage.com/car/6098/Force-India-VJM08-Mercedes.html",
    "https://www.ultimatecarpage.com/car/6094/Lotus-E23-Hybrid-Mercedes.html",
    "https://www.ultimatecarpage.com/car/6092/McLaren-MP4-30-Honda.html",
    "https://www.ultimatecarpage.com/car/6095/Mercedes-Benz-W06-Hybrid.html",
    "https://www.ultimatecarpage.com/car/6100/Red-Bull-Racing-RB11-Renault.html",
    "https://www.ultimatecarpage.com/car/6097/Sauber-C34-Ferrari.html",
    "https://www.ultimatecarpage.com/car/6099/Toro-Rosso-STR10-Renault.html",
    "https://www.ultimatecarpage.com/car/6093/Williams-FW37-Mercedes.html",
    "https://www.ultimatecarpage.com/car/5765/Caterham-CT05-Renault.html",
    "https://www.ultimatecarpage.com/car/5771/Ferrari-F14-T.html",
    "https://www.ultimatecarpage.com/car/5764/Force-India-VJM07-Mercedes.html",
    "https://www.ultimatecarpage.com/car/5772/Lotus-E22-Renault.html",
    "https://www.ultimatecarpage.com/car/5777/Marussia-MR03-Ferrari.html",
    "https://www.ultimatecarpage.com/car/5770/McLaren-MP4-29-Mercedes.html",
    "https://www.ultimatecarpage.com/car/5773/Mercedes-Benz-W05.html",
    "https://www.ultimatecarpage.com/car/5774/Red-Bull-Racing-RB10-Renault.html",
    "https://www.ultimatecarpage.com/car/5776/Sauber-C33-Ferrari.html",
    "https://www.ultimatecarpage.com/car/5775/Toro-Rosso-STR9-Renault.html",
    "https://www.ultimatecarpage.com/car/5768/Williams-FW36-Mercedes.html",
    "https://www.ultimatecarpage.com/car/5436/Caterham-CT03-Renault.html",
    "https://www.ultimatecarpage.com/car/5421/Ferrari-F138.html",
    "https://www.ultimatecarpage.com/car/5427/Force-India-VJM06-Mercedes.html",
    "https://www.ultimatecarpage.com/car/5420/Lotus-E21-Renault.html",
    "https://www.ultimatecarpage.com/car/5422/McLaren-MP4-28-Mercedes.html",
    "https://www.ultimatecarpage.com/car/5423/Mercedes-Benz-W04.html",
    "https://www.ultimatecarpage.com/car/5424/Red-Bull-Racing-RB9-Renault.html",
    "https://www.ultimatecarpage.com/car/5426/Sauber-C32-Ferrari.html",
    "https://www.ultimatecarpage.com/car/5435/Toro-Rosso-STR8-Ferrari.html",
    "https://www.ultimatecarpage.com/car/5425/Williams-FW35-Renault.html",
    "https://www.ultimatecarpage.com/car/5081/Caterham-CT01-Renault.html",
    "https://www.ultimatecarpage.com/car/5091/Ferrari-F2012.html",
    "https://www.ultimatecarpage.com/car/5092/Force-India-VJM05-Mercedes.html",
    "https://www.ultimatecarpage.com/car/5144/HRT-F112-Cosworth.html",
    "https://www.ultimatecarpage.com/car/5087/Lotus-E20-Renault.html",
    "https://www.ultimatecarpage.com/car/5089/McLaren-MP4-27-Mercedes.html",
    "https://www.ultimatecarpage.com/car/5122/Mercedes-Benz-W03.html",
    "https://www.ultimatecarpage.com/car/5097/Red-Bull-Racing-RB8-Renault.html",
    "https://www.ultimatecarpage.com/car/5094/Sauber-C31-Ferrari.html",
    "https://www.ultimatecarpage.com/car/5099/Toro-Rosso-STR7-Ferrari.html",
    "https://www.ultimatecarpage.com/car/5088/Williams-FW34-Renault.html",
    "https://www.ultimatecarpage.com/car/4718/Ferrari-F150th-Italia.html",
    "https://www.ultimatecarpage.com/car/4732/Force-India-VJM04-Mercedes.html",
    "https://www.ultimatecarpage.com/car/4733/HRT-F111-Cosworth.html",
    "https://www.ultimatecarpage.com/car/4730/McLaren-MP4-26-Mercedes.html",
    "https://www.ultimatecarpage.com/car/4719/Mercedes-Benz-W02.html",
    "https://www.ultimatecarpage.com/car/4721/Red-Bull-Racing-RB7-Renault.html",
    "https://www.ultimatecarpage.com/car/4724/Renault-R31.html",
    "https://www.ultimatecarpage.com/car/4720/Sauber-C30-Ferrari.html",
    "https://www.ultimatecarpage.com/car/4722/Team-Lotus-T128-Renault.html",
    "https://www.ultimatecarpage.com/car/4725/Toro-Rosso-STR6-Ferrari.html",
    "https://www.ultimatecarpage.com/car/4731/Virgin-MVR-02-Cosworth.html",
    "https://www.ultimatecarpage.com/car/4726/Williams-FW33-Cosworth.html",
    "https://www.ultimatecarpage.com/car/8600/Alpine-A524-Renault.html",
    "https://www.ultimatecarpage.com/car/8599/Aston-Martin-AMR24-Mercedes.html",
    "https://www.ultimatecarpage.com/car/8595/Ferrari-SF-24.html",
    "https://www.ultimatecarpage.com/car/8601/Haas-VF-24-Ferrari.html",
    "https://www.ultimatecarpage.com/car/8593/McLaren-MCL38-Mercedes.html",
    "https://www.ultimatecarpage.com/car/8594/Mercedes-AMG-W15-E-Performance.html",
    "https://www.ultimatecarpage.com/car/8597/RB-VCARB-01-RBPT-Honda.html",
    "https://www.ultimatecarpage.com/car/8596/Red-Bull-Racing-RB20-RBPT-Honda.html",
    "https://www.ultimatecarpage.com/car/8592/Sauber-C44-Ferrari.html",
    "https://www.ultimatecarpage.com/car/8598/Williams-FW46-Mercedes.html",
    "https://www.ultimatecarpage.com/car/8435/Alfa-Romeo-Racing-C43-Ferrari.html",
    "https://www.ultimatecarpage.com/car/8440/AlphaTauri-AT04-RBPT-Honda.html",
    "https://www.ultimatecarpage.com/car/8443/Alpine-A523-Renault.html",
    "https://www.ultimatecarpage.com/car/8442/Aston-Martin-AMR23-Mercedes.html",
    "https://www.ultimatecarpage.com/car/8438/Ferrari-SF-23.html",
    "https://www.ultimatecarpage.com/car/8444/Haas-VF-23-Ferrari.html",
    "https://www.ultimatecarpage.com/car/8436/McLaren-MCL60-Mercedes.html",
    "https://www.ultimatecarpage.com/car/8437/Mercedes-AMG-W14-E-Performance.html",
    "https://www.ultimatecarpage.com/car/8439/Red-Bull-Racing-RB19-RBPT-Honda.html",
    "https://www.ultimatecarpage.com/car/8441/Williams-FW45-Mercedes.html",
    "https://www.ultimatecarpage.com/car/8263/Alfa-Romeo-Racing-C42-Ferrari.html",
    "https://www.ultimatecarpage.com/car/8268/AlphaTauri-AT03.html",
    "https://www.ultimatecarpage.com/car/8271/Alpine-A522-Renault.html",
    "https://www.ultimatecarpage.com/car/8270/Aston-Martin-AMR22-Mercedes.html",
    "https://www.ultimatecarpage.com/car/8266/Ferrari-F1-75.html",
    "https://www.ultimatecarpage.com/car/8272/Haas-VF-22-Ferrari.html",
    "https://www.ultimatecarpage.com/car/8264/McLaren-MCL36-Mercedes.html",
    "https://www.ultimatecarpage.com/car/8265/Mercedes-AMG-W13-E-Performance.html",
    "https://www.ultimatecarpage.com/car/8267/Red-Bull-Racing-RB18.html",
    "https://www.ultimatecarpage.com/car/8269/Williams-FW44-Mercedes.html",
    "https://www.ultimatecarpage.com/car/8095/Alfa-Romeo-Racing-C41-Ferrari.html",
    "https://www.ultimatecarpage.com/car/8100/AlphaTauri-AT02-Honda.html",
    "https://www.ultimatecarpage.com/car/8103/Alpine-A521-Renault.html",
    "https://www.ultimatecarpage.com/car/8102/Aston-Martin-AMR21-Mercedes.html",
    "https://www.ultimatecarpage.com/car/8098/Ferrari-SF21.html",
    "https://www.ultimatecarpage.com/car/8104/Haas-VF-21-Ferrari.html",
    "https://www.ultimatecarpage.com/car/8096/McLaren-MCL35M-Mercedes.html",
    "https://www.ultimatecarpage.com/car/8097/Mercedes-Benz-W12-E-Performance.html",
    "https://www.ultimatecarpage.com/car/8099/Red-Bull-Racing-RB16B-Honda.html",
    "https://www.ultimatecarpage.com/car/8101/Williams-FW43B-Mercedes.html"
]

# Initialize an empty DataFrame with Name and Text columns
df = pd.DataFrame(columns=["Name", "Text"])

# Iterate over each URL
for url in urls:
    print(url)
    # Send a request to the page
    response = requests.get(url)
    response.encoding = 'utf-8'
    soup = BeautifulSoup(response.text, 'html.parser')

    # Extract the car name
    car_name = soup.find('span', class_='carheader').text.strip()

    # Extract the car text
    intelliTxt_span = soup.find('span', id='intelliTxt')
    if intelliTxt_span:
        text = intelliTxt_span.get_text(separator="\n", strip=True)
    else:
        text = None  # Handle case where text is not found

    # Create a new DataFrame for the current URL's data
    new_data = pd.DataFrame({"Name": [car_name], "Text": [text]})

    # Concatenate the new DataFrame with the existing one
    df = pd.concat([df, new_data], ignore_index=True)

# Display the DataFrame
print(df)

# Save the DataFrame to a CSV file
df.to_csv('carData.csv', index=False)
